In [4]:
import numpy as np

In [5]:
list1=[10,20,30]
list1

[10, 20, 30]

In [6]:
arr1=np.array(list1)
arr1

array([10, 20, 30])

In [7]:
type(list1)

list

In [8]:
type(arr1)

numpy.ndarray

In [9]:
arr2=np.arange(10,20,2)
arr2

array([10, 12, 14, 16, 18])

In [10]:
list2=[40,50,60]
list2

[40, 50, 60]

In [11]:
list3=[list1,list2]
list3

[[10, 20, 30], [40, 50, 60]]

In [12]:
arr3=np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [13]:
arr3.shape

(2, 3)

In [16]:
arr4=np.array([[[1,2,3],[4,5,6,]],[[7,8,9],[1,2,3]]])
arr4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]]])

In [17]:
arr4.shape

(2, 2, 3)

In [19]:
list1*3


[10, 20, 30, 10, 20, 30, 10, 20, 30]

In [20]:
arr1*3

array([30, 60, 90])

In [21]:
arr4*3

array([[[ 3,  6,  9],
        [12, 15, 18]],

       [[21, 24, 27],
        [ 3,  6,  9]]])

In [22]:
arr2=np.array(list2)
arr2

array([40, 50, 60])

In [23]:
arr1*arr2


array([ 400, 1000, 1800])

In [24]:
arr1*arr4

array([[[ 10,  40,  90],
        [ 40, 100, 180]],

       [[ 70, 160, 270],
        [ 10,  40,  90]]])

In [26]:
list=[1,2,3,4,5,6,7,8,9,11,12,15]
arr=np.array(list)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 15])

In [27]:
arr.shape

(12,)

In [29]:
lista=[1,2,3,4]
listb=[2,3,4,5]
listc=[4,5,6,7]
listd=[lista,listb,listc]
arra=np.array(listd)
arra

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [30]:
arra.shape

(3, 4)

In [34]:
arr5=np.array([[[1,2,3,4],[2,3,4,5],[1,2,3,4],[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[2,3,4,5],[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
arr5

array([[[1, 2, 3, 4],
        [2, 3, 4, 5],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [2, 3, 4, 5],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [35]:
arr5.shape

(2, 5, 4)

In [40]:
arr3[1][2]

60

In [41]:
arr3[1]

array([40, 50, 60])

In [42]:
arr3[1:]

array([[40, 50, 60]])

In [43]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [44]:
for x in arr3:
    print (x)
    

[10 20 30]
[40 50 60]


In [45]:
for x in arr3:
    for num in x:
        print(num)

10
20
30
40
50
60


In [46]:
for x in np.nditer(arr3):
    print(x)

10
20
30
40
50
60
